# Generated by Django 5.1.6 on 2025-02-27 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_auth', '0003_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
    ]
