# Generated by Django 5.1.6 on 2025-02-27 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='created_by',
        ),
    ]
